name: flytectl-setup-action
#run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  install-flytectl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: unionai-oss/flytectl-setup-action@master
      - name: Setup demo cluster
        run: flytectl demo start
      - name: Setup flytectl config
        run: flytectl config init
      - name: Register Core example
        run: |
          FLYTESNACKS_VERSION=$(curl --silent "https://api.github.com/repos/flyteorg/flytectl/releases/latest" | jq -r .tag_name)
          flytectl register files -p flytesnacks -d development --archive https://github.com/flyteorg/flytesnacks/releases/download/$FLYTESNACKS_VERSION/flytesnacks-core.tgz  --version v1
 



